# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KT8EKahX-Zli08EKmrHnjibYsDXhT8cd
"""

import spacy

# Load the English NLP model from spaCy
nlp = spacy.load("en_core_web_sm")

def chatbot():
    print("Chatbot: Hi there! I'm your friendly chatbot. How can I help you today?")

    while True:
        user_input = input("You: ").lower()

        # Exit condition
        if user_input in ["exit", "bye", "quit"]:
            print("Chatbot: It was nice chatting with you. Goodbye!")
            break

        # Process the input with spaCy
        doc = nlp(user_input)

        # Extract entities
        entities = {ent.label_: ent.text for ent in doc.ents}

        # Example responses based on entities
        if "PERSON" in entities:
            print(f"Chatbot: Nice to meet you, {entities['PERSON']}!")
        elif "DATE" in entities:
            print(f"Chatbot: Oh, you're talking about {entities['DATE']}. What's special about it?")
        elif "GPE" in entities:
            print(f"Chatbot: {entities['GPE']} sounds like an interesting place!")
        elif "ORG" in entities:
            print(f"Chatbot: I've heard a lot about {entities['ORG']}!")
        else:
            # Default responses for general inputs
            if "hello" in user_input or "hi" in user_input:
                print("Chatbot: Hello! How are you?")
            elif "how are you" in user_input:
                print("Chatbot: I'm just a program, but I'm doing great! Thanks for asking. What about you?")
            elif "weather" in user_input:
                print("Chatbot: I'm not sure, but you can check a weather app or website!")
            elif "time" in user_input:
                from datetime import datetime
                current_time = datetime.now().strftime("%I:%M %p")
                print(f"Chatbot: The current time is {current_time}.")
            else:
                print("Chatbot: I'm sorry, I don't understand that. Could you rephrase or ask something else?")

if __name__ == "__main__":
    chatbot()